### PR TITLE
Document how to install on OS X.

### PR DESCRIPTION
**Pull request by timkuijsten**
Document steps to install on OS X.

### CODE REVIEW

**Comment by timkuijsten** [comment]
Took me a while to figure out how to do this. If done right, not a lot of steps are needed.

**Comment by skx** [comment]
Much appreciated, thank you.

**Comment by timkuijsten** [comment]
You're welcome.

Unfortunately when starting lumail2 on my mac the keys are not working. It looks like it doesn't detect key presses. So i.e. I can't use TAB, H or quit with q or Q, only ^C does abort.

Furthermore the colors are really light which makes it hard to read on my terminal with the [solarized](http://ethanschoonover.com/solarized) light theme (but still debuggable ;)).

I've tried both the latest in git master, as well as the tagged v2.7 release. This is on the latest stable OS X, 10.11.5. Hopefully I'll find time later to further investigate..

**Comment by skx** [comment]
I thought this had been resolved in [this comment](https://github.com/lumail/lumail2/issues/134#issuecomment-231241536)?

In short /etc/lumail2/lumail2.lua must exist.  That will then load /etc/lumail2/lib/*.lua - one of which has the keybindings in it.

**Comment by timkuijsten** [comment]
That does the trick! I copied all the libs and a user config, except /etc/lumail2/lumail2.lua. :)

It does bring me further, but now I get the following error:
```shell
[11779 / 11779] - MYMAILDIR
lumail2(24523,0x7fff7aa69000) malloc: *** error for object 0x7fde35b00d30: incorrect checksum for freed object - object was probably modified after being freed.
                                                                                                                                                                *** set a breakpoint in malloc_error_break to debug
                                  Abort trap: 6
```
I've copied lumail2.user.lua to ~/.lumail2/lumail2.lua and the only change I've made is pointing `maildir.prefix` to my maildir. My maildir is of the form ~/Mail/my@email.com.

**Comment by skx** [comment]
Ugh that looks very much like a memory corruption bug, which is a lot harder for me to diagnose from here.

You might find that running under a debugger shows where it dies, which would be useful information, but unfortunately I'm not at all familiar with such things under Mac OS X - I don't even know if you use gdb!

There is a debug target you can build `make lumail2-debug` which might have more information, and might give you a core-dump allowing a stack-trace when it dies, but again I'm not sure how such things are done on Macs.  :(

**Pull request merged**
