### PR TITLE
Mail threading

### PR DESCRIPTION
**Pull request by fischerling**
My work on mail threading in pure lua mentioned in #253.

### CODE REVIEW

**Comment by fischerling** [comment]
I finally got the time to finish the thread sort.

It is implemented in sort_messages() to minimize its diff.
A Description of it's behaviour can be found in the last commit message.

With the current implementation there is no thread related functionality
possible, like deleting a whole thread.

**Comment by skx** [comment]
Thanks for your continued work on this.  I'll pull today and have a play with it.

**Comment by fischerling** [comment]
Should the options:

* promote unread threads
* what message is used to compare threads

be exposed to the user through ```Config``` ?

**Comment by fischerling** [comment]
I removed the option to promote threads containing unread messages entirely.
`promote_unread` was confusing, broken and useless.

**Comment by skx** [comment]
I've had a quick play with this and I like it.

What more needs to be done before you're happy that it can be merged?  Documentation?  Testing?  Speedup(s)?

**Comment by fischerling** [comment]
We have to change the way message format strings are cached, because the thread sort is inserting
its indentation into it. So if the sorting_method is changed the cached formats don't get updated.

1. Documentation is enough in my opinion, though it is diffuse.
    + Config values are documented in lumail2.user.lua
    + The threads method is mentioned along the other sorting methods in API.md 
    + The algorithm is documented in its source file and the commit messages.
    + Should I write additional documentation ?
2. I checked the results only manually against mutt with my own maildirs. So some
additional/automated testing would be great.
3. Certainly there are possible speedups. But I don't know any ;) Of course
we could make threading more prominent and integrate it into the c++ core.

**Comment by skx** [comment]
I apologize, but I've just accepted a smaller merge-request and that made this conflict.

If you could fix so it merges cleanly I'll accept this immediately - you've done a good job, and I think it should be included.  No doubt it will need further work in the future, but my previous testing showed it was good enough for the moment.

**Comment by skx** [comment]
> Of course we could make threading more prominent and integrate it into the c++ core.

This would speed things up a lot.

Right now most of the UI delay I see is relating to fetching messages and filtering them, such that we see "new", "today", or "all".  In the past this was done in the core - but moving it to lua was done to improve flexibility.  I'm still unsure if I should change my mind - I think more people have contributed Lua changes than C++ ones, so leaving it as-is is perhaps easier for others.

**Comment by fischerling** [comment]
@skx Rebased :)

**Comment by skx** [comment]
Much appreciated, thank-you.

**Pull request merged**
