### PR TITLE
Fix Message:is_new() to better match the C++ version.

### PR DESCRIPTION
**Pull request by jugglerchris**
* Previously, it returned false if the S(een) flag was set, even
if the N(ew) flags was set.

### CODE REVIEW

**Comment by jugglerchris** [comment]
Ok I meant to keep the extra commits as a separate PR!  I'll branch and split them if you prefer.
The extra commits fix the nested MIME part handling by ditching the foreach stuff in favour of just recursively adding children starting from the root.

**Comment by jugglerchris** [comment]
To test I added this into message_view() after `parts = msg:parts()`
```lua
   if true then
       local function showpart(part, indent)
           local result = indent .. "type="..part:type().." size="..tostring(part:size()).." is_attachment="..tostring(part:is_attachment()).." filename="..tostring(part:filename())
           return result
       end
       local function parts2string(parts, indent)
           local result = ""
           for _,part in ipairs(parts) do
               result = result .. showpart(part, indent) .. "\n"
               local children = part:children()
               if type(children) == type({}) then
                   result = result .. parts2string(children, indent .. "   ")
               end
           end
           return result
       end
       output = output .. "Parts: [ [\n"
       output = output .. parts2string(parts, "   ")
       output = output .. "Parts: ] ]\n"
   end
```
I'll forward the e-mail test case.

**Comment by skx** [comment]
Separate pull-requests would be preferred _if_ the changes were controversial, complex, or possibly wrong.

An initial glance showed they looked fine to me, and I trust you to commit directly to master if you need to make any "emergency" fixups anyway :)

**Comment by skx** [comment]
For the mime-part handling I guess there are three places to change, all on the lua-side:

* attachment_view() - For showing the parts in attachment-mode.
* save_mime_part() - To make sure we iterate in the same way such that the offset works.
* view_mime_part() - For the same reason.

**Pull request merged**
