### PR TITLE
Add Lumail2's Lua library path to package.path to properly load libs.

### PR DESCRIPTION
**Pull request by vifino**
Hello.

I am having some issues trying to getting lumail2 to work properly here.
Hopefully, some I'll be able to resolve these issues.

This is the first PR to this project. I am quite unfamiliar with the code base and style, plus I have not used
C++ for a while.

This PR adds lumails lib path to package.path to be able to load the libraries no matter where we are in the PWD, which was not the case in every situation before.

PS: I am very much open to criticism. I tried to match the style of the other code in the files I worked with, however, `make indent` wanted to apply many changes, which I thought would not be appropriate.

I hope this may be of use.

### CODE REVIEW

**Comment by skx** [comment]
Thanks for your contribution!  The core of this code looks good, and I will attend to the `make indent` issue shortly.

I think it needs an update, but only minor.  The specific problem I have is that I have two versions of lumail I use:

* The globally installed version.
* A version in ~/.  (Which means ~/lib/ for the load-path, and ~/lumail2.lua).

I need the global version for reading my mail, and I need the local version to avoid any regressions and to compare performance.  That's why the load-path tries to decide at run-time whether to use `/etc/lumail2/lib` vs `./lib`.  The latter allows testing from git checkouts too.

With your change applied a local version would always use the global library, rather than the modified local copy.

I'd be happy to apply your work, but I'd want to add `--load-path` to allow over-ridding.  So for example:

       /usr/bin/lumail2  -- # Runs as per normal
       /usr/bin/lumail2  --load-path=$HOME/lib  # Runs with load-path set to ./lib/.

**Comment by skx** [comment]
I'll accept now, and add a command-line override shortly.

Thanks again :)

**Comment by skx** [comment]
Fixed in [this commit](https://github.com/lumail/lumail2/commit/71868c1f7cd5c22f1587b5beca4381db142c1698)

**Comment by vifino** [comment]
Hello.

No problem, once I get lumail2 properly running here, I'll give you all the praise you deserve!

I plan to make a PR in the future to allow lumail2 to work fine with LuaJIT, given lua52 compat specific options enabled. I am currently running into some issues, however, I expect to overcome them soon.

Thanks for your hard work (and merging my probably less than ideal PR)!

**Comment by skx** [comment]
I look forward to seeing more, then!

(But it should "just work" with luajit; that's what I'm using right now ..)

**Comment by vifino** [comment]
Weird. I get very weird errors with the /etc/lumail2/lumail2.lua:
`An error was caught /etc/lumail2/lumail2.lua:63: attempt to call method 'append' (a nil value)` while trying to execute something via the `:` REPL. (By the way, I am making that prettier ;) )

**Pull request merged**
